# Generated by Django 5.0.1 on 2024-01-07 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cusid', models.IntegerField(primary_key=True, serialize=False)),
                ('cusname', models.TextField(max_length=40)),
                ('cusaddress', models.TextField(max_length=100)),
                ('phoneno', models.IntegerField(unique=True)),
                ('cusmail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.TextField(max_length=40)),
                ('dob', models.DateField()),
                ('empmail', models.EmailField(max_length=254, unique=True)),
                ('empdesignation', models.TextField(max_length=40)),
                ('empsalary', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('carid', models.IntegerField(primary_key=True, serialize=False)),
                ('carname', models.TextField(max_length=50)),
                ('carprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carmodel', models.TextField(max_length=50)),
                ('yom', models.TextField(max_length=5)),
                ('fueltype', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('invoiceno', models.IntegerField(primary_key=True, serialize=False)),
                ('sdate', models.DateTimeField(auto_now_add=True)),
                ('mop', models.CharField(max_length=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scarid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carprojapp.inventory')),
                ('scusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carprojapp.customer')),
                ('spempid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carprojapp.employee')),
            ],
        ),
    ]
